# Generated by Django 3.1.6 on 2021-04-12 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentapp', '0003_auto_20210412_1451'),
        ('placeapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='documentapp.document')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placeapp.place')),
            ],
        ),
    ]
