# Generated by Django 3.1.6 on 2021-04-12 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='path',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
