# Generated by Django 3.1.6 on 2021-04-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0003_auto_20210412_1451'),
        ('pathapp', '0002_path_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='documentapp.document', unique=True),
        ),
    ]
