# Generated by Django 3.1.6 on 2021-04-12 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0003_auto_20210412_1451'),
        ('placeapp', '0001_initial'),
        ('pathapp', '0003_auto_20210412_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='path', to='documentapp.document'),
        ),
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('document', 'place')},
        ),
    ]
