# Generated by Django 3.1.6 on 2021-04-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=20)),
                ('document_color', models.CharField(max_length=20)),
                ('document_map', models.CharField(max_length=100)),
                ('document_date', models.DateTimeField(auto_now_add=True)),
                ('document_liked', models.IntegerField(default=0)),
                ('document_private', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_profile', to='profileapp.profile')),
                ('profile_friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_profile_friend', to='profileapp.profile')),
            ],
        ),
    ]
