# Generated by Django 3.1.6 on 2021-04-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='like',
            field=models.IntegerField(default=0),
        ),
    ]
