# Generated by Django 3.2 on 2021-05-05 09:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profileapp', '0001_initial'),
        ('documentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='profile_friend',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='document_profile_friend', to='profileapp.profile'),
        ),
    ]
