# Generated by Django 3.1.6 on 2021-04-12 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentapp', '0002_document_like'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='like',
            new_name='liked',
        ),
    ]
