# Generated by Django 3.1.6 on 2021-04-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=20)),
                ('place_rate', models.CharField(max_length=20)),
                ('place_photo', models.CharField(max_length=100)),
                ('place_date', models.DateTimeField(auto_now_add=True)),
                ('place_latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('place_private', models.BooleanField(default=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place', to='profileapp.profile')),
            ],
        ),
    ]
