# Generated by Django 3.1.6 on 2021-04-13 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='rate',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
