# Generated by Django 3.2 on 2021-05-07 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='save',
            name='save_comment',
        ),
    ]
