# Generated by Django 3.1.6 on 2021-04-25 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documentapp', '0001_initial'),
        ('profileapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_data', models.DateTimeField()),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like', to='documentapp.document')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profileapp.profile')),
            ],
            options={
                'unique_together': {('profile', 'document')},
            },
        ),
    ]
