# Generated by Django 3.2 on 2021-05-07 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likeapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like_data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
