# Generated by Django 3.1.6 on 2021-05-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maximumapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maximum',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
